
#Configurations related to materials.
[materials]
	#Should the mod find gem materials without ores.
	gemPlain = true
	#Should the mod find dust materials without ores.
	dustPlain = true
	#Should the mod find crystal materials with ores.
	crystal = true
	#Should the mod find ingot materials with ores.
	ingot = true
	#Should the mod find ingot materials without ores.
	ingotPlain = true
	#Should the mod find crystal materials without ores.
	crystalPlain = true
	#Should the mod find dust materials with ores.
	dust = true
	#Should the mod find gem materials with ores.
	gem = true

#Configurations related to material overrides.
[materialOverrides]
	#List of materials that should be crystals.
	crystal = []
	#List of materials that should be dusts.
	dust = ["glowstone", "redstone"]
	#List of materials that should be gems.
	gem = ["diamond", "emerald", "lapis", "prismarine", "quartz"]

#Configurations related to item selection.
[itemSelection]
	#List of mods that are preferred when selecting items in recipes.
	preferredMods = ["minecraft"]

#Configurations related to block tags.
[blockTags]
	#List of block tags that should be considered as defined.
	customDefined = []
	#List of block tags that should not be added.
	blacklist = []

#Configurations related to item tags.
[itemTags]
	#List of item tags that should be considered as defined.
	customDefined = []
	#List of item tags that should not be added.
	blacklist = []

#Configurations related to fluid tags.
[fluidTags]
	#List of fluid tags that should be considered as defined.
	customDefined = []
	#List of fluid tags that should not be added.
	blacklist = []

#Configurations related to entity type tags.
[entityTypeTags]
	#List of entity type tags that should be considered as defined.
	customDefined = []
	#List of entity type tags that should not be added.
	blacklist = []

#Configurations related to recipes.
[recipes]
	#List of recipes that should not be added.
	blacklist = ["jaopca:immersiveengineering.ore_to_dust_hammer.silicon", "jaopca:immersiveengineering.ore_to_dust_hammer.desh", "jaopca:immersiveengineering.ore_to_dust_hammer.iridium", "jaopca:immersiveengineering.material_to_plate_hammer.desh", "jaopca:immersiveengineering.material_to_plate_hammer.zinc", "jaopca:immersiveengineering.ore_to_dust_hammer.starmetal", "jaopca:immersiveengineering.ore_to_dust_hammer.thallasium", "jaopca:immersiveengineering.material_to_plate_hammer.brass", "jaopca:immersiveengineering.material_to_plate_hammer.tin", "jaopca:immersiveengineering.plate_to_wire.lead", "jaopca:immersiveengineering.plate_to_wire.gold", "jaopca:immersiveengineering.plate_to_wire.iron", "jaopca:immersiveengineering.material_to_plate_hammer.bronze", "jaopca:immersiveengineering.material_to_plate_hammer.invar", "jaopca:immersiveengineering.material_to_plate_hammer.signalum", "jaopca:immersiveengineering.material_to_plate_hammer.lumium", "jaopca:immersiveengineering.material_to_plate_hammer.enderium", "jaopca:immersiveengineering.material_to_plate_hammer.silicon", "jaopca:immersiveengineering.material_to_plate_hammer.titanium", "jaopca:immersiveengineering.material_to_plate_hammer.iridium", "jaopca:immersiveengineering.material_to_plate_hammer.netherite", "jaopca:thermal_expansion.dust_to_material.titanium", "jaopca:create.ore_to_material_crushing.ametrine", "jaopca:create.ore_to_material_crushing.sulfur", "jaopca:create.ore_to_material_crushing.niter", "jaopca:create.ore_to_crushed_crushing.cobalt", "jaopca:create.ore_to_material_crushing.cinnabar", "jaopca:create.ore_to_crushed_crushing.netherite_scrap", "jaopca:create.ore_to_material_crushing.apatite", "jaopca:thermal_expansion.material_to_dust.fluix", "jaopca:mekanism.material_to_dust.fluix", "jaopca:create.ore_to_crushed_milling.cobalt", "jaopca:create.ore_to_crushed_milling.netherite_scrap", "jaopca:mekanism.ore_to_dust.iridium", "jaopca:thermal_expansion.ore_to_dust.iridium", "jaopca:appliedenergistics2.ore_to_dust.iridium", "jaopca:mekanism.dirty_dust_to_dust.iridium", "jaopca:mekanism.clump_to_dirty_dust.iridium", "jaopca:mekanism.shard_to_clump.iridium", "jaopca:mekanism.ore_to_clump.iridium", "jaopca:mekanism.crystal_to_shard.iridium", "jaopca:mekanism.ore_to_shard.iridium", "jaopca:mekanism.clean_slurry_to_crystal.iridium", "jaopca:mekanism.dirty_to_clean_slurry_iridium", "jaopca:mekanism.ore_to_dirty_slurry.iridium", "jaopca:thermal_expansion.ore_to_material_smelter.iridium", "jaopca:thermal_expansion.dust_to_material.signalum", "jaopca:appliedenergistics2.ore_to_dust.starmetal", "jaopca:tconstruct.molten_to_material_gold_cast.iridium", "jaopca:tconstruct.molten_to_material_sand_cast.iridium", "jaopca:tconstruct.ore_to_molten.iridium", "jaopca:create.material_to_plate.zinc"]
	#List of recipes by regex that should not be added.
	regexBlacklist = []

#Configurations related to loot tables.
[lootTables]
	#List of loot tables that should not be added.
	blacklist = []

#Configurations related to advancements.
[advancements]
	#List of advancements that should not be added.
	blacklist = []

#Configurations related to color generation.
[colors]
	#The gamma value used to blend colors.
	gammaValue = 2.0
	#Should colors of all materials be reset on next startup.
	resetColors = false

#Configurations related to material localization.
[materialLocalization]
	#The update interval of localization files in days.
	updateInterval = 3.0
	#Should the mod check for material localization updates.
	checkL10nUpdates = true

