events.listen('item.tags', function (event) {
	event.get('mana-and-artifice:bookshelves')
		.add('#forge:bookshelves')
		.add('betterendforge:mossy_glowshroom_bookshelf')
		.add('betterendforge:lacugrove_bookshelf')
		.add('betterendforge:end_lotus_bookshelf')
		.add('betterendforge:pythadendron_bookshelf')
		.add('betterendforge:dragon_tree_bookshelf')
		.add('betterendforge:tenanea_bookshelf')
		.add('betterendforge:helix_tree_bookshelf')
		.add('betterendforge:umbrella_tree_bookshelf')
		.add('betterendforge:jellyshroom_bookshelf')
		.add('securitycraft:reinforced_bookshelf')
		.add('tardis:alabaster_bookshelf')
		.add('tardis:ebony_bookshelf')
})