events.listen('item.tags', function (event) {
	event.get('twilightforest:portal/activator').add('botania:mana_diamond')
	event.get('twilightforest:portal/activator').remove('#forge:gems/diamond')
	event.get('twilightforest:portal/edge').add('#forge:dirt')
	event.get('byg_planks').add('twilightforest:tower_wood')
	event.get('byg_planks').add('twilightforest:twilight_oak_planks')
	event.get('byg_planks').add('twilightforest:canopy_planks')
	event.get('byg_planks').add('twilightforest:mangrove_planks')
	event.get('byg_planks').add('twilightforest:dark_planks')
	event.get('byg_planks').add('twilightforest:time_planks')
	event.get('byg_planks').add('twilightforest:trans_planks')
	event.get('byg_planks').add('twilightforest:mine_planks')
	event.get('byg_planks').add('twilightforest:sort_planks')
})