events.listen('item.tags', function (event) {
	event.get('twilightforest:portal/activator')
		.remove('#forge:gems/diamond')
		.add('botania:terrasteel_ingot')
	event.get('twilightforest:portal/edge').add('#forge:dirt')
	event.get('byg_planks')
		.add('twilightforest:tower_wood')
		.add('twilightforest:twilight_oak_planks')
		.add('twilightforest:canopy_planks')
		.add('twilightforest:mangrove_planks')
		.add('twilightforest:dark_planks')
		.add('twilightforest:time_planks')
		.add('twilightforest:trans_planks')
		.add('twilightforest:mine_planks')
		.add('twilightforest:sort_planks')
})