
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 15
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 5
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 2

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 5
		#The amount of items transferred
		#Range: > 1
		basic = 8
		#The amount of items transferred
		#Range: > 1
		improved = 10
		#The amount of items transferred
		#Range: > 1
		advanced = 20
		#The amount of items transferred
		#Range: > 1
		ultimate = 40

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 1250
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 1250
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 2500
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 5000
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 10000

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 50000
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 50000
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 75000
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 150000
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 200000

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 1250
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 1250
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 2500
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 5000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 10000

