
["Tardis Configurations"]
	#List of dimensions Tardis cannot travel to, everything else is allowed
	#Seperate every entry except the last one with commas
	blacklistedDims = ['twilightforest:skylight_forest', 'appliedenergistics2:spatial_storage', 'tardis:moon', 'tardis:space']
	#If two TARDISes are closer than this number, they are considered 'colliding'
	#When they collide, a Time Ram event is initiated
	collisionRange = 16

["Interior Change Configuration"]
	#Sets the seconds of cooldown time between each changing of the Tardis Interior
	interiorChangeCooldownTime = 60
	#Sets the amount of Artron fuel required between each changing of the Tardis Interior
	interiorChangeArtronUse = 100

["Machines Configuration"]
	#Defines how much Forge Energy is needed for 1 Artron Unit
	#Used to balance out the Artron Converter Block
	#This is a float value, allows for decimals
	FEtoAURate = 1000.0

["Vortex Manipulator (VM) Configurations"]

	["Vortex Manipulator (VM) Configurations"."Travel Configurations"]
		#Toggle whether to use the Whitelist. By default, uses the Blacklist
		toggleVMWhitelistDims = false
		#List of dimensions the VM can travel to, anything else is not allowed
		#Seperate every entry except the last one with commas
		whitelistedVMDims = ["minecraft:overworld", "minecraft:the_nether", "minecraft:the_end"]
		#List of dimensions the VM cannot travel to, everything else is allowed
		#Seperate every entry except the last one with commas
		blacklistedVMDims = ["modID:dimensionName"]
		#Sets the maximum Teleport Range the Vortex Manipulator can teleport to
		vmTeleportRange = 10000

	["Vortex Manipulator (VM) Configurations".Limitations]
		#Sets the seconds of cooldown time needed between uses of the Vortex Manipulator
		vmCooldownTime = 10
		#Sets the effect side effects experienced after using the Vortex Manipulator
		vmSideEffects = ["minecraft:nausea", "minecraft:weakness"]
		#Sets the duration in seconds for each effect in the above value
		#The order of the numbers should match the effect you are setting the duration for.
		vmSideEffectTime = [5, 10]

	["Vortex Manipulator (VM) Configurations"."Fuel Control"]
		#Sets the base value that scales for how much fuel is used by the VM
		#Fuel Usage = YourInputValue + (YourMultiplier * TeleportDistance)
		#E.g. If you want the fuel usage to be 20 charge per 100 blocks, you would set the base value to 20 - (0.005 * 100)
		vmBaseFuelUsage = 5
		#Sets the figure that scales how much fuel is used by the VM per amount of seconds set by user
		#Fuel Usage = YourBaseInputValue + (YourMultiplier * TeleportDistance)
		#E.g. If you want the fuel usage to be 20 charge per 100 blocks, you would set the base value to 20 - (0.005 * 100)
		vmFuelUsageMultiplier = 0.024
		#Sets the seconds of time that must elapse before the VM uses up fuel
		vmFuelUsageTime = 1

["Sonic Screwdriver"]

	["Sonic Screwdriver"."Block Interactions"]
		#Toggle whether sonics can detonate TNT
		detonate_tnt = true
		#Toggle whether sonics can toggle Lamps
		redstone_lamps = true
		#Toggle whether sonics can open doors
		open_doors = true
		#Toggle whether sonics can open Trap doors
		open_trapdoors = true

	["Sonic Screwdriver"."Entity Interactions"]
		#Toggle whether sonics can detonate Creepers
		detonate_creeper = true
		#Toggle whether sonics can Shear Sheep
		shear_sheep = true
		#Toggle whether sonics can dismantle Skeleton like entities
		dismantle_skeletons = true
		#Toggle whether sonics can ink Squids
		ink_squid = true

	["Sonic Screwdriver".Tardis]
		#Toggle whether sonics can tell the Tardis where to land
		coordinate_tardis = true

