
#Project: Vibrant Journeys settings
[Settings]

	#World Gen Settings
	[Settings."World Gen"]
		seaOats = true
		cattails = true
		barkMushrooms = true
		cobwebs = true
		bushes = true
		glowcap = true
		netherNettles = true
		fallenTrees = true
		#Seagrass in lakes
		moreSeagrass = true
		#Denser river grass
		moreGrassInRivers = true

		[Settings."World Gen".Groundcover]
			rocks = true
			twigs = true
			fallenLeaves = true
			bones = true
			charredBones = true
			iceChunks = true
			pinecones = true
			seashells = true
			# % chance of groundcover placement
			#Range: 0 ~ 100
			groundcoverChance = 100
			#Groundcover Biome Blacklist, example: ["minecraft:plains", "minecraft:beach"]
			groundcoverBlacklist = []

	#Mob Spawn Settings
	[Settings."Mob Spawns"]
		#Tropical fish in jungles
		jungleTropicalFish = true

	#Biome Settings
	[Settings.Biomes]
		overgrownSpires = true
		verdantSands = true

