
#Ores
[worldgen]
	#Generate Carbonate Ore
	generateCarbonate = false
	#Generate Dolomite
	generateDolomite = false
	#Generate Sulfide Ore
	generateSulfide = false
	#Generate Oxide Ore
	generateOxide = false
	#Generate Phosphate Ore
	generatePhosphate = false
	#Generate Sulfate Ore
	generateSulfate = false
	#Generate Sulfur Ore
	generateSulfur = false

