
#Generation Setting
[Generation_Settings]
	#Use Replaceable Block Tag? Could have performance impact!
	#Default: true
	replaceableTag = true
	#Replace cobblestone? Replaces dungeon cobble stone for example.
	#Default: true
	replaceCobble = true
	#Disable rock replacement
	#Default: false
	disableGeneration = false
	#Disable nether generation
	#Default: false
	disableNetherGeneration = false
	#Enables debug mode. Takes more time to generate.
	#Default : false
	debug = false
	#Replace ores? 
	#Default: true
	replaceOres = true
	#Replacement behavior of dirt.
	#NONE: does not replace dirt
	#HILL: only replace on hilly biomes(default)
	#ALL: replace all dirt regardless of biome
	#Allowed Values: NONE, HILLS, ALL
	dirtReplacement = "HILLS"

