
[world_gen]
	#Config to toggle the generation of arms in snow biomes
	arms = false
	#Configure whether Catacombs Structures spawn. This will require a restart when changed.
	genCatacombs = false
	#Configure whether Graveyard Structures spawn. This will require a restart when changed.
	genGraveyard = false
	#Configure whether the mods ores spawn. This MAY require a restart when changed.
	genOres = false

[spawn]
	#Note: A list of biomes where angels should spawn.
	allowedBiomes = ["boss_tools:mercury_biome", "boss_tools:mars_biome"]
	#Angel spawn type
	#Allowed Values: MONSTER, CREATURE, AMBIENT, WATER_CREATURE, WATER_AMBIENT, MISC
	spawnType = "MONSTER"
	#The maximum amount of angels per biome
	#Range: 1 ~ 100
	maximumSpawn = 3
	#The angel spawn spawn weight
	#Range: 1 ~ 100
	spawnWeight = 3
	#The minimum amount of angels per biome
	#Range: 1 ~ 100
	minimumSpawn = 1

[angel]
	#if enabled, Only pickaxes and generators will work on the angels
	pickaxeOnly = true
	#The damage dealt by an angel
	#Range: 1.0 ~ 1.7976931348623157E308
	damage = 12.0
	#XP gained from angels
	#Range: > 1
	xpGained = 50
	#Determines the range the angels will look for players within, personally, I'd stay under 100
	#Range: 1 ~ 100
	stalkRange = 65
	#The maximum range a angel can break blocks within
	#Range: 1 ~ 120
	blockBreakRange = 5
	#If this is enabled, baby angels will blow out light items from the players hand
	torchBlowOut = false
	#if enabled, angels will freeze when they see one another. (Impacts performance a bit)
	freezeOnAngel = false
	#If this is enabled, angels will break blocks (If gamerules allow) - !!!! BLOCK BLACKLISTING: You may be looking for a config option in order to stop certain blocks from being broken. You can do this with a datapack using weeping_angels:angel_proof
	blockBreaking = false
	#Toggle seen sounds
	playSeenSounds = true
	#If this is enabled, the timey wimey detector can blow up chickens when in use randomly
	chickenGoboom = true
	#Non-child angels play scraping sounds when moving, this toggles that
	playScrapeSound = true
	#Damage Type For Angels
	#Allowed Values: NOTHING, ANY_PICKAXE_AND_GENERATOR_ONLY, ANY_PICKAXE_ONLY, DIAMOND_AND_ABOVE_PICKAXE_ONLY, GENERATOR_ONLY
	damageType = "DIAMOND_AND_ABOVE_PICKAXE_ONLY"
	#Determines the angels move speed
	#Range: 0.1 ~ 1.7976931348623157E308
	angelMovementSpeed = 0.5

[teleport]
	#Note: This a list of dimensions that angels should NOT teleport you to.
	notAllowedDimensions = ["minecraft:the_end"]
	#Should Angels target creative players?
	aggroCreative = false
	#The maximum range a user can be teleported by the Angels
	#Range: > 1
	teleportRange = 3000
	#If this is enabled, angel teleporting can also tp the player to other dimensions
	angelDimTeleport = false
	#Teleport Type - STRUCTURES: Teleports you to Structures Only - DONT: No Teleporting, only damage - RANDOM: Anywhere
	#Allowed Values: STRUCTURES, RANDOM_PLACE, DONT
	teleportType = "RANDOM_PLACE"
	#just teleport. no damage.
	justTeleport = false

[block]
	#This config option toggles whether angels can spawn from Statues/Plinths when they receive a redstone signal
	spawnFromBlocks = false

[misc]
	#Toggle whether santa hats are shown at Xmas
	showSantaHatsAtXmas = true
	#Toggle certain angel models (Only applies to Entity)
	allowedAngelTypes = ["DISASTER_MC", "DOCTOR", "ED", "ED_ANGEL_CHILD", "A_DIZZLE", "DYING", "VILLAGER", "VIO_1", "VIO_2"]
	#Toggle certain angel variants (Only applies to Entity)
	allowedVariants = ["weeping_angels:gold", "weeping_angels:diamond", "weeping_angels:iron", "weeping_angels:mossy", "weeping_angels:normal", "weeping_angels:basalt", "weeping_angels:rusted", "weeping_angels:rusted_no_arm", "weeping_angels:rusted_no_wing", "weeping_angels:rusted_no_head", "weeping_angels:dirt", "weeping_angels:emerald", "weeping_angels:copper", "weeping_angels:lapis_lazuli", "weeping_angels:quartz"]

