
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 5461309
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false

[create]
	#The byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

